### ISSUE TITLE
Can I evaluate some videos by using pre-trained model  ? 

### ISSUE THREAD

**Issue by SHAIIM04** [cxliu0/PET#14]
Thanks for releasing your code and making good efforts.

I would ask you, Can I use a pre-trained model to evaluate some videos? I want to know the crowd count of persons for each frame.

**Comment by cxliu0** [comment]
Sure. You can use the pre-trained model to estimate the number of people in each frame. 

However, the counting performance may not be guaranteed, because there may exist a domain gap between the videos and the data that used to train the model.

**Comment by SHAIIM04** [comment]
Thanks for your responses 

Is there a code for this task can you provide it to me?

Best regrds

**Comment by cxliu0** [comment]
This repository supports the evaluation of a single image. You can refer to [eval.py](https://github.com/cxliu0/PET/blob/main/eval.py#L116) and [engine.py](https://github.com/cxliu0/PET/blob/main/engine.py#L131).

For videos, you need to rewrite the dataloader before evaluation.
