### ISSUE TITLE
Calculation of FLOPs

### ISSUE THREAD

**Issue by 2226450890** [cxliu0/PET#16]
Dear author,

I have tried to calculate the FLOPs for PET, but after much effort could not calculate it successfully, can you provide its calculation?

Thank you very much for your response.

**Comment by cxliu0** [comment]
The computational cost of our approach depends on the input image, as the point-query quadtree is dynamically constructed during inference. Therefore, the FLOPs also vary from image to image. You may try to use the first layer of the point-query quadtree to compute FLOPs.
