### ISSUE TITLE
About the location map and its eval metrics

### ISSUE THREAD

**Issue by xiaotongtongxue** [cxliu0/PET#21]
@cxliu0 It is a very excellent job, but when I run your eval code, the point location of an object within the image has a big distance between the actual location. Sometimes, it presents a strange matrix-like shape that does not reflect the true location at all. 

By the way, I have run the training code for 2k epochs,  but I always get these-like results. Can I get your WeChat and talk deeply with you?

Thanks a lot!

**Comment by cxliu0** [comment]
Did you properly train the model on your dataset? Perhaps the training process went wrong, which led to weird results. You may email me for discussion.
