### ISSUE TITLE
the problem of predicting multiple points for one head

### ISSUE THREAD

**Issue by KonstantinLihota** [cxliu0/PET#22]
Hello. When using my data, I had a problem, which is that the network often predicts 2-3 points that are very close to each other for one head. Tell us, have you ever had such a problem in your experiments, and how did you deal with it?

**Comment by cxliu0** [comment]
In practice, the model typically predicts one point for each head. 

For your problem, it is hard to tell what the problem is without an example. Perhaps the model is not properly trained. You may inspect the training process and check if something went wrong.

**Comment by KonstantinLihota** [comment]
I will give a few explanations, one point appears from a sparse zone, the other from a dense one. For some reason, predictions from different zones are not split. We are talking about predictions during training. Tell me if you have ever encountered such a problem?

**Comment by cxliu0** [comment]
In certain scenarios, duplicate predictions may occur.
