### ISSUE TITLE
Epoch problem

### ISSUE THREAD

**Issue by YZGod666** [cxliu0/PET#27]
The default epoch parameter of your model code is set to 1500. When training the data set of Shanghai Science and Technology, I found that it has achieved good training results before 300epoch. What is the reason for you to set this 1500epoch?

**Comment by cxliu0** [comment]
ShanghaiTech is a small crowd counting dataset, so it is unnecessary to train the model for 1500 epochs. However, for large-scale datasets, it usually takes a longer time to train a good model.
