### ISSUE TITLE
Default number of epochs

### ISSUE THREAD

**Issue by MoetezKd** [cxliu0/PET#3]
Hi, 
Thanks for the contribution.
I've seen that the default number of epochs is 1500 which is uncommon. I was wondering if you used this amount of epochs in your main experiments for the paper and if so is there is an explanation about it? 
Thanks for your help!

**Comment by cxliu0** [comment]
The number of epochs was selected based on the experiments. We found that setting the number of epochs to 1500 is generally sufficient to train a good model.
