### ISSUE TITLE
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

### ISSUE THREAD

**Issue by xiaotongtongxue** [cxliu0/PET#4]
The code running in the 5th epoch showed the above problem. The pet.py in models: points_queries_win = points_queries_win[:, v_idx].reshape(-1, 2)

**Comment by cxliu0** [comment]
It seems that ```points_queries_win``` and ```v_idx``` were not in the same device. Did you run the model on CPU? You can check the status of ```points_queries_win``` and ```v_idx```.

**Comment by heeeyk** [comment]
Add `v_idx = v_idx.cpu()` before `points_queries_win = points_queries_win[:, v_idx].reshape(-1, 2)`.

**Comment by cxliu0** [comment]
Glad to see you solve this issue. As I expected, this error occurs when the model is running on the CPU.
