### ISSUE TITLE
Can it run TRANCOS?

### ISSUE THREAD

**Issue by sullivantee** [cxliu0/PET#6]
As the title says, I want to use TRANCOS to train the model, 
If it can run TRANCOS, what file do I need to change? and what do I need to change?

**Comment by cxliu0** [comment]
Our approach is applicable to other counting tasks, and you can train PET on the TRANCOS dataset.

You need to customize the dataset :
1. Customize the dataloader for TRANCOS dataset. Please refer to [SHA.py](https://github.com/cxliu0/PET/blob/main/datasets/SHA.py) to define your own dataset. 
2. Define TRANCOS in [datasets/__init__.py](https://github.com/cxliu0/PET/blob/main/datasets/__init__.py).
3. Modify [train.sh](https://github.com/cxliu0/PET/blob/main/train.sh) to train PET on TRANCOS
