### ISSUE TITLE
SHB result

### ISSUE THREAD

**Issue by mru4913** [cxliu0/PET#9]
Hi，there:

I retrained SH-B with the code and the hyper-parameters given; However the best MAE was 7.6, which is far different than the result given by the paper. Is there any tricks I should conduct in order to replicate your result?

**Comment by cxliu0** [comment]
Different environments may result in different optimal epochs. You may try to train the model for 2000 or 3000 epochs (optionally, add ```torch.backends.cudnn.deterministic = True``` before training for reproducibility).
In general, SHB and SHA share the same training parameters.
